<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * fiche_fraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fiche_fraisRepository extends \Doctrine\ORM\EntityRepository
{
}
