<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * frais_forfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class frais_forfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
