<?php

namespace GSB\VisiteurBundle\Repository;

/**
 * ligne_frais_hors_forfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligne_frais_hors_forfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
